version: "3"
services:
    postgres-db:
        container_name: postgres-db
        image: 'postgres:latest'
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "password"
